name: sunahara
favicon: null
layout_spectrum: 0.27406
typography_spectrum: 0.24547
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#34375b'
    - '#fefefe'
    - '#adafcb'
    - '#6b6c7d'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
